# Generated by Django 4.1.4 on 2022-12-28 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('sposob_platnosc', models.CharField(blank=True, max_length=200, null=True)),
                ('cena_podatku', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('koszt_wysylki', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sum_cena', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('oplacone', models.BooleanField(default=False)),
                ('kiedy_oplacone', models.DateTimeField(blank=True, null=True)),
                ('dostarczone', models.BooleanField(default=False)),
                ('kiedy_dostarczone', models.DateTimeField(blank=True, null=True)),
                ('kiedy_zamowione', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZamowionyProdukt',
            fields=[
                ('nazwa', models.CharField(blank=True, max_length=200, null=True)),
                ('ilosc', models.IntegerField(blank=True, default=0, null=True)),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('zdjecie', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('produkt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.produkt')),
                ('zamowienie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.zamowienie')),
            ],
        ),
        migrations.CreateModel(
            name='AdresWysylki',
            fields=[
                ('adres', models.CharField(blank=True, max_length=200, null=True)),
                ('miasto', models.CharField(blank=True, max_length=200, null=True)),
                ('kod_pocztowy', models.CharField(blank=True, max_length=200, null=True)),
                ('kraj', models.CharField(blank=True, max_length=200, null=True)),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('zamowienie', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.zamowienie')),
            ],
        ),
    ]
