# Generated by Django 4.1.4 on 2022-12-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_zamowienie_zamowionyprodukt_adreswysylki'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='zdjecie_prod',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
